[package]
name = "drpurge"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]

[dependencies]
byte-unit = "1.1.0"
docopt = "0.8.1"
serde = "1.0.15"
serde_derive = "1.0"
walkdir = "2.0.1"